# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'elektro.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(371, 600)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 351, 271))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 131, 17))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 111, 17))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(100, 10, 151, 17))
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(10, 190, 81, 17))
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(10, 160, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(10, 210, 331, 41))
        self.label_5.setObjectName("label_5")
        self.textEdit_1 = QtWidgets.QTextEdit(self.frame)
        self.textEdit_1.setGeometry(QtCore.QRect(10, 60, 331, 31))
        self.textEdit_1.setObjectName("textEdit_1")
        self.textEdit_2 = QtWidgets.QTextEdit(self.frame)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 120, 331, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(10, 290, 351, 261))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit_3.setGeometry(QtCore.QRect(10, 30, 331, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 331, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(10, 70, 291, 17))
        self.label_7.setObjectName("label_7")
        self.textEdit_4 = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit_4.setGeometry(QtCore.QRect(10, 90, 331, 31))
        self.textEdit_4.setObjectName("textEdit_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 130, 89, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(10, 160, 51, 17))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(10, 200, 67, 17))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(10, 240, 81, 17))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(100, 160, 241, 17))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(100, 200, 241, 17))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(100, 240, 241, 17))
        self.label_13.setObjectName("label_13")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 371, 22))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.pushButton.clicked.connect(self.hitung)
        self.pushButton_2.clicked.connect(self.hitung_2)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def hitung(self):
        volt = float(self.textEdit_1.toPlainText())
        print(volt)
        ampere = float(self.textEdit_2.toPlainText())
        print(ampere)
        langkah1 = volt*ampere
        print(langkah1)
        langkah2 = str(langkah1)
        self.label_5.setText(langkah2 + " Watt")

    def hitung_2(self):
        volt = self.textEdit_1.toPlainText()
        print(volt)
        ampere = self.textEdit_2.toPlainText()
        print(ampere)
        leda = self.textEdit_3.toPlainText()
        print(leda)
        ledv = self.textEdit_4.toPlainText()
        print(ledv)
        svolt = float (volt)
        sampere = float (ampere)
        sleda = float (leda)
        sledv = float (ledv)
        nseri = svolt/sledv
        nparalel = sampere/sleda
        nled = nseri*nparalel
        nseri2 = str(nseri)
        nparalel2 = str(nparalel)
        nled2 = str(nled)
        print(nseri)
        print(nparalel)
        self.label_11.setText(nseri2 + " seri")
        self.label_12.setText(nparalel2 + " paralel")
        self.label_13.setText(nled2 + " biji")

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "LED GrowLight, koma pakai titik"))
        self.label_3.setText(_translate("mainWindow", "Kuat arus (Ampere)"))
        self.label_2.setText(_translate("mainWindow", "Tegangan (Volt)"))
        self.label.setText(_translate("mainWindow", "Hitung daya adaptor"))
        self.label_4.setText(_translate("mainWindow", "Hasil (watt)"))
        self.pushButton.setText(_translate("mainWindow", "Hitung"))
        self.label_5.setText(_translate("mainWindow", "?"))
        self.label_6.setText(_translate("mainWindow", "datasheet kebutuhan arus LED(Ampere)"))
        self.label_7.setText(_translate("mainWindow", "datasheet kebutuhan tegangan LED(Volt)"))
        self.pushButton_2.setText(_translate("mainWindow", "Hitung"))
        self.label_8.setText(_translate("mainWindow", "Nseri:"))
        self.label_9.setText(_translate("mainWindow", "Nparalel:"))
        self.label_10.setText(_translate("mainWindow", "Total LED:"))
        self.label_11.setText(_translate("mainWindow", "?"))
        self.label_12.setText(_translate("mainWindow", "?"))
        self.label_13.setText(_translate("mainWindow", "?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())

